gmp: configure and acinclude.m4: fix -std=c23 build failure
Add prototype to configure test function as c23 removes unprototyped
functions.

gcc-15 switched to -std=c23 by default:

    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

As a result `configure` fails with:
    conftest.c: In function 'f':
    conftest.c:12:48: error: too many arguments to function 'g'; expected 0, have 6
       12 | for(i=0;i<1;i++){if(e(got,got,9,d[i].n)==0)h();g(i,d[i].src,d[i].n,got,d[i].want,9);if(d[i].n)h();}}
          |                                                ^ ~
    conftest.c:7:6: note: declared here
        7 | void g(){}
          |      ^

Upstream: hg log --patch --rev 18477:8e7bb4ae7a18
Link: https://gmplib.org/list-archives/gmp-bugs/2024-November/005550.html
Link: https://gmplib.org/list-archives/gmp-devel/2025-January/006281.html
Signed-off-by: Rudi Heitbaum <rudi@heitbaum.com>